SRCS = \
config/Config.cpp\
config/Location.cpp\
config/parse_config.cpp\
core/Server.cpp\
core/Client.cpp\
core/EvMa.cpp\
static/resp_codes.cpp\
static/mime_types.cpp\
main.cpp\
exchange/Response.cpp\
exchange/Request.cpp\
modules/CGI.cpp\
modules/Autoindex.cpp\
util/int_pow.cpp\
util/socket_manips.cpp\
util/time_in_ms.cpp\
util/str_manips.cpp\
util/log.cpp\
util/raw_str.cpp\
