SRCS = \
static/mime_types.cpp\
static/resp_codes.cpp\
config/Location.cpp\
config/Config.cpp\
config/parse_config.cpp\
exchange/Response.cpp\
exchange/Request.cpp\
core/Server.cpp\
core/EvMa.cpp\
core/Client.cpp\
utils/str_manips.cpp\
utils/raw_str.cpp\
utils/socket_manips.cpp\
utils/int_pow.cpp\
utils/time_in_ms.cpp\
utils/log.cpp\
modules/Autoindex.cpp\
modules/CGI.cpp\
main.cpp\
